### ISSUE TITLE
Feature Request: Oneline/Simplified View

### ISSUE THREAD

**Issue by wsdmatty** [Necoro/arch-log#1]
Give the option of getting just the first line of the current output, (date, hash, commitmsg first line) and skip the commitmgs full text and dash separator. 

There's no particular reason why this is *necessary* but I'd find a one-line output easier to parse mentally. Maybe have a * or some other indicator that the first line of the commitmsg is not the entire message, for people wanting to actually read the details.

For an example, I have a 'pretty' git log display I use for a game i develop for:

```
* d6e1d40 Fri Jul 14 21:09:02 2023 -0400 (HEAD -> vigorcheck, origin/vigorcheck) do_vigor: checks if vigor is currently active (closes #994)
* 08b5d56 Fri Jun 23 21:37:30 2023 -0400 (tag: 3.75.0, origin/master, origin/HEAD, live/master, master) do_fleshcraft: more intuitive argument naming (#981)
* f48be3d Fri Jun 23 21:20:05 2023 -0400 do_fleshcraft: fixed typo (#981)
* 90cced8 Fri Jun 23 15:21:01 2023 -0400 fleshcraft: Adjusted disc level and syntax (fixes #981)
* 3ca5b42 Wed Jun 21 17:28:52 2023 -0400 channel: wording update (#984)
* 9bc4b60 Tue Jun 20 22:28:18 2023 -0400 channel: success gives quintessence, adjusted quint cost (closes #984)
* 1f25415 Tue Jun 20 22:02:57 2023 -0400 channel: botch/fail/magic check (#984)
```

This would allow users to quickly glance over a larger number of commits when using the -n option.

**Comment by Necoro** [comment]
How about?: 

(with tags / Arch)
![grafik](https://github.com/Necoro/arch-log/assets/68708/26c52aed-723d-4eb4-908f-38fd9eda1b18)

(without tags / AUR)
![grafik](https://github.com/Necoro/arch-log/assets/68708/f99617c1-6a1a-412f-ba10-ede9bceae935)

Tbh, after seeing it like this, I prefer it over the verbose version. So perhaps I make it the standard...

Note that I shortened the date time to only include the date, because I figured that the time is mostly irrelevant.

**Comment by Necoro** [comment]
> I am tempted to poke around in your code and break it in interesting ways.

Feel free to do so :)
