### ISSUE TITLE
Error if package is available in testing repos, too

### ISSUE THREAD

**Issue by df8oe** [Necoro/arch-log#4]
I am runnig a system with testing repos. Now I want to test arch-log on a package which exists in "extra" and in "extra-testing". An error message is thrown:

arch-log linux-zen
ERROR: error fetching from Arch: more than one package info found: [{PkgName:linux-zen PkgBase:linux-zen Repo:extra} {PkgName:linux-zen PkgBase:linux-zen Repo:extra-testing}]

But how can I tell arch-log to use specific repo?

**Comment by Necoro** [comment]
Good point, I haven't tested it with multiple repos.

**Comment by df8oe** [comment]
I thought so.... It would be a way to specify repo and package like

extra-testing/linux-zen

**Comment by Necoro** [comment]
Hi @df8oe,

it took a while, because the repository info in Arch is ... not as expected: There is no obvious connection, thus I constructed one via version info and tag names. Hope that'll work out.

When a package is now in multiple repos, it is show like this:
![Example Repo](https://necoro.dev/data/example_arch-log_repos.png)

It is also possible to restrict the repo: Either by explicitly passing the `--repo` parameter, or by using the `repo/pkg` syntax.
For convenience `aur` is also recognized as a repo and is thus identical to passing `--aur`
